# Generated by Django 4.2.21 on 2025-05-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintUpdate',
        ),
    ]
