<<<<<<< HEAD
# Generated by Django 4.2.21 on 2025-05-20 10:33
=======
# Generated by Django 4.2.21 on 2025-05-20 07:10
>>>>>>> 2a27909603471dee8d8a6a51f7643673b08fbc7d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplaintUpdate',
        ),
    ]
